name: Run Tests (Ubuntu)

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/*
      - src/**
      - build.zig
      - build.zig.zon

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: (Z) Install Zig
      uses: mlugg/setup-zig@v2
      with:
        version: 0.15.1

    - name: Run tests
      shell: bash
      run: zig build test
